apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycrudapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycrudapi
  template:
    metadata:
      labels:
        app: mycrudapi
    spec:
      containers:
      - name: mycrudapi
        image: abhishekcrm/mycrudapi:latest 
        imagePullPolicy: Always  
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mycrudapi-service
spec:
  selector:
    app: mycrudapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

